myGoogleApiKey = ''
instantInformationEnabled = 1
fontSize = 120
mainText = 'KJV'
mainB = 1
mainC = 1
mainV = 1
studyText = 'NET'
studyB = 43
studyC = 3
studyV = 16
commentaryText = 'CBSC'
commentaryB = 43
commentaryC = 3
commentaryV = 16
topic = 'EXLBT'
dictionary = 'EAS'
encyclopedia = 'ISB'
book = 'Boyce'
bookSearchString = ''
historyRecordAllowed = 50
currentRecord = {'main': 0, 'study': 0}
history = {'main': ['Genesis 1:1'], 'study': ['BIBLE:::NET:::John 3:16']}