fontSize = 120
mainText = 'KJV'
mainB = 1
mainC = 1
mainV = 1
studyText = 'KJV'
studyB = 43
studyC = 1
studyV = 1
historyRecordAllowed = 30
currentRecord = {'main': 0, 'study': 0}
history = {'main': ['Genesis 1:1'], 'study': ['BIBLE:::KJV:::John 1:1']}